name: CocoaPods Release

on:
  workflow_dispatch
    
jobs:
  cocoapods-release:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: CocoaPods Release
        with:
          ref: main
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod trunk push Qonversion.podspec
